name: courses
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^9.2.1
  adaptive_platform_ui: ^0.1.111
  flutter_svg: ^2.3.0
  flutter_svg_provider: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.8
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Stara
      fonts:
        - asset: assets/fonts/Stara-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Stara-Bold.otf
          weight: 700
        - asset: assets/fonts/Stara-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Stara-Medium.otf
          weight: 500
